# Generated by Django 2.2.10 on 2021-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='empsize',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AddField(
            model_name='business',
            name='emp_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='OwnerDetails',
        ),
    ]
